// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: record.proto

package com.chi.ssetest.protos;

public final class TestRecord {
  private TestRecord() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TestExecutionRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:stock_testing.TestExecutionRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string jobID = 1;</code>
     */
    java.lang.String getJobID();
    /**
     * <code>string jobID = 1;</code>
     */
    com.google.protobuf.ByteString
        getJobIDBytes();

    /**
     * <code>string runnerID = 2;</code>
     */
    java.lang.String getRunnerID();
    /**
     * <code>string runnerID = 2;</code>
     */
    com.google.protobuf.ByteString
        getRunnerIDBytes();

    /**
     * <code>string testcaseID = 3;</code>
     */
    java.lang.String getTestcaseID();
    /**
     * <code>string testcaseID = 3;</code>
     */
    com.google.protobuf.ByteString
        getTestcaseIDBytes();

    /**
     * <code>string recordID = 4;</code>
     */
    java.lang.String getRecordID();
    /**
     * <code>string recordID = 4;</code>
     */
    com.google.protobuf.ByteString
        getRecordIDBytes();

    /**
     * <code>bool isPass = 5;</code>
     */
    boolean getIsPass();

    /**
     * <code>int64 startTime = 6;</code>
     */
    long getStartTime();

    /**
     * <code>int64 endTime = 7;</code>
     */
    long getEndTime();

    /**
     * <code>string resultStr = 8;</code>
     */
    java.lang.String getResultStr();
    /**
     * <code>string resultStr = 8;</code>
     */
    com.google.protobuf.ByteString
        getResultStrBytes();

    /**
     * <code>string exceptionStr = 9;</code>
     */
    java.lang.String getExceptionStr();
    /**
     * <code>string exceptionStr = 9;</code>
     */
    com.google.protobuf.ByteString
        getExceptionStrBytes();
  }
  /**
   * Protobuf type {@code stock_testing.TestExecutionRecord}
   */
  public  static final class TestExecutionRecord extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:stock_testing.TestExecutionRecord)
      TestExecutionRecordOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TestExecutionRecord.newBuilder() to construct.
    private TestExecutionRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestExecutionRecord() {
      jobID_ = "";
      runnerID_ = "";
      testcaseID_ = "";
      recordID_ = "";
      resultStr_ = "";
      exceptionStr_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TestExecutionRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              jobID_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              runnerID_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              testcaseID_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              recordID_ = s;
              break;
            }
            case 40: {

              isPass_ = input.readBool();
              break;
            }
            case 48: {

              startTime_ = input.readInt64();
              break;
            }
            case 56: {

              endTime_ = input.readInt64();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              resultStr_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              exceptionStr_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chi.ssetest.protos.TestRecord.internal_static_stock_testing_TestExecutionRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chi.ssetest.protos.TestRecord.internal_static_stock_testing_TestExecutionRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chi.ssetest.protos.TestRecord.TestExecutionRecord.class, com.chi.ssetest.protos.TestRecord.TestExecutionRecord.Builder.class);
    }

    public static final int JOBID_FIELD_NUMBER = 1;
    private volatile java.lang.Object jobID_;
    /**
     * <code>string jobID = 1;</code>
     */
    public java.lang.String getJobID() {
      java.lang.Object ref = jobID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobID_ = s;
        return s;
      }
    }
    /**
     * <code>string jobID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getJobIDBytes() {
      java.lang.Object ref = jobID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RUNNERID_FIELD_NUMBER = 2;
    private volatile java.lang.Object runnerID_;
    /**
     * <code>string runnerID = 2;</code>
     */
    public java.lang.String getRunnerID() {
      java.lang.Object ref = runnerID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        runnerID_ = s;
        return s;
      }
    }
    /**
     * <code>string runnerID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRunnerIDBytes() {
      java.lang.Object ref = runnerID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        runnerID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TESTCASEID_FIELD_NUMBER = 3;
    private volatile java.lang.Object testcaseID_;
    /**
     * <code>string testcaseID = 3;</code>
     */
    public java.lang.String getTestcaseID() {
      java.lang.Object ref = testcaseID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        testcaseID_ = s;
        return s;
      }
    }
    /**
     * <code>string testcaseID = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTestcaseIDBytes() {
      java.lang.Object ref = testcaseID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testcaseID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECORDID_FIELD_NUMBER = 4;
    private volatile java.lang.Object recordID_;
    /**
     * <code>string recordID = 4;</code>
     */
    public java.lang.String getRecordID() {
      java.lang.Object ref = recordID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recordID_ = s;
        return s;
      }
    }
    /**
     * <code>string recordID = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRecordIDBytes() {
      java.lang.Object ref = recordID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recordID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISPASS_FIELD_NUMBER = 5;
    private boolean isPass_;
    /**
     * <code>bool isPass = 5;</code>
     */
    public boolean getIsPass() {
      return isPass_;
    }

    public static final int STARTTIME_FIELD_NUMBER = 6;
    private long startTime_;
    /**
     * <code>int64 startTime = 6;</code>
     */
    public long getStartTime() {
      return startTime_;
    }

    public static final int ENDTIME_FIELD_NUMBER = 7;
    private long endTime_;
    /**
     * <code>int64 endTime = 7;</code>
     */
    public long getEndTime() {
      return endTime_;
    }

    public static final int RESULTSTR_FIELD_NUMBER = 8;
    private volatile java.lang.Object resultStr_;
    /**
     * <code>string resultStr = 8;</code>
     */
    public java.lang.String getResultStr() {
      java.lang.Object ref = resultStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resultStr_ = s;
        return s;
      }
    }
    /**
     * <code>string resultStr = 8;</code>
     */
    public com.google.protobuf.ByteString
        getResultStrBytes() {
      java.lang.Object ref = resultStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXCEPTIONSTR_FIELD_NUMBER = 9;
    private volatile java.lang.Object exceptionStr_;
    /**
     * <code>string exceptionStr = 9;</code>
     */
    public java.lang.String getExceptionStr() {
      java.lang.Object ref = exceptionStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exceptionStr_ = s;
        return s;
      }
    }
    /**
     * <code>string exceptionStr = 9;</code>
     */
    public com.google.protobuf.ByteString
        getExceptionStrBytes() {
      java.lang.Object ref = exceptionStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exceptionStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getJobIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jobID_);
      }
      if (!getRunnerIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, runnerID_);
      }
      if (!getTestcaseIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, testcaseID_);
      }
      if (!getRecordIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, recordID_);
      }
      if (isPass_ != false) {
        output.writeBool(5, isPass_);
      }
      if (startTime_ != 0L) {
        output.writeInt64(6, startTime_);
      }
      if (endTime_ != 0L) {
        output.writeInt64(7, endTime_);
      }
      if (!getResultStrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, resultStr_);
      }
      if (!getExceptionStrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, exceptionStr_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getJobIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, jobID_);
      }
      if (!getRunnerIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, runnerID_);
      }
      if (!getTestcaseIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, testcaseID_);
      }
      if (!getRecordIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, recordID_);
      }
      if (isPass_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isPass_);
      }
      if (startTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, startTime_);
      }
      if (endTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, endTime_);
      }
      if (!getResultStrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, resultStr_);
      }
      if (!getExceptionStrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, exceptionStr_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.chi.ssetest.protos.TestRecord.TestExecutionRecord)) {
        return super.equals(obj);
      }
      com.chi.ssetest.protos.TestRecord.TestExecutionRecord other = (com.chi.ssetest.protos.TestRecord.TestExecutionRecord) obj;

      if (!getJobID()
          .equals(other.getJobID())) return false;
      if (!getRunnerID()
          .equals(other.getRunnerID())) return false;
      if (!getTestcaseID()
          .equals(other.getTestcaseID())) return false;
      if (!getRecordID()
          .equals(other.getRecordID())) return false;
      if (getIsPass()
          != other.getIsPass()) return false;
      if (getStartTime()
          != other.getStartTime()) return false;
      if (getEndTime()
          != other.getEndTime()) return false;
      if (!getResultStr()
          .equals(other.getResultStr())) return false;
      if (!getExceptionStr()
          .equals(other.getExceptionStr())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + JOBID_FIELD_NUMBER;
      hash = (53 * hash) + getJobID().hashCode();
      hash = (37 * hash) + RUNNERID_FIELD_NUMBER;
      hash = (53 * hash) + getRunnerID().hashCode();
      hash = (37 * hash) + TESTCASEID_FIELD_NUMBER;
      hash = (53 * hash) + getTestcaseID().hashCode();
      hash = (37 * hash) + RECORDID_FIELD_NUMBER;
      hash = (53 * hash) + getRecordID().hashCode();
      hash = (37 * hash) + ISPASS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsPass());
      hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartTime());
      hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEndTime());
      hash = (37 * hash) + RESULTSTR_FIELD_NUMBER;
      hash = (53 * hash) + getResultStr().hashCode();
      hash = (37 * hash) + EXCEPTIONSTR_FIELD_NUMBER;
      hash = (53 * hash) + getExceptionStr().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.chi.ssetest.protos.TestRecord.TestExecutionRecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chi.ssetest.protos.TestRecord.TestExecutionRecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chi.ssetest.protos.TestRecord.TestExecutionRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chi.ssetest.protos.TestRecord.TestExecutionRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chi.ssetest.protos.TestRecord.TestExecutionRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chi.ssetest.protos.TestRecord.TestExecutionRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chi.ssetest.protos.TestRecord.TestExecutionRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chi.ssetest.protos.TestRecord.TestExecutionRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chi.ssetest.protos.TestRecord.TestExecutionRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.chi.ssetest.protos.TestRecord.TestExecutionRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chi.ssetest.protos.TestRecord.TestExecutionRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chi.ssetest.protos.TestRecord.TestExecutionRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.chi.ssetest.protos.TestRecord.TestExecutionRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code stock_testing.TestExecutionRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:stock_testing.TestExecutionRecord)
        com.chi.ssetest.protos.TestRecord.TestExecutionRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chi.ssetest.protos.TestRecord.internal_static_stock_testing_TestExecutionRecord_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chi.ssetest.protos.TestRecord.internal_static_stock_testing_TestExecutionRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chi.ssetest.protos.TestRecord.TestExecutionRecord.class, com.chi.ssetest.protos.TestRecord.TestExecutionRecord.Builder.class);
      }

      // Construct using com.chi.ssetest.protos.TestRecord.TestExecutionRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        jobID_ = "";

        runnerID_ = "";

        testcaseID_ = "";

        recordID_ = "";

        isPass_ = false;

        startTime_ = 0L;

        endTime_ = 0L;

        resultStr_ = "";

        exceptionStr_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chi.ssetest.protos.TestRecord.internal_static_stock_testing_TestExecutionRecord_descriptor;
      }

      @java.lang.Override
      public com.chi.ssetest.protos.TestRecord.TestExecutionRecord getDefaultInstanceForType() {
        return com.chi.ssetest.protos.TestRecord.TestExecutionRecord.getDefaultInstance();
      }

      @java.lang.Override
      public com.chi.ssetest.protos.TestRecord.TestExecutionRecord build() {
        com.chi.ssetest.protos.TestRecord.TestExecutionRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.chi.ssetest.protos.TestRecord.TestExecutionRecord buildPartial() {
        com.chi.ssetest.protos.TestRecord.TestExecutionRecord result = new com.chi.ssetest.protos.TestRecord.TestExecutionRecord(this);
        result.jobID_ = jobID_;
        result.runnerID_ = runnerID_;
        result.testcaseID_ = testcaseID_;
        result.recordID_ = recordID_;
        result.isPass_ = isPass_;
        result.startTime_ = startTime_;
        result.endTime_ = endTime_;
        result.resultStr_ = resultStr_;
        result.exceptionStr_ = exceptionStr_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chi.ssetest.protos.TestRecord.TestExecutionRecord) {
          return mergeFrom((com.chi.ssetest.protos.TestRecord.TestExecutionRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chi.ssetest.protos.TestRecord.TestExecutionRecord other) {
        if (other == com.chi.ssetest.protos.TestRecord.TestExecutionRecord.getDefaultInstance()) return this;
        if (!other.getJobID().isEmpty()) {
          jobID_ = other.jobID_;
          onChanged();
        }
        if (!other.getRunnerID().isEmpty()) {
          runnerID_ = other.runnerID_;
          onChanged();
        }
        if (!other.getTestcaseID().isEmpty()) {
          testcaseID_ = other.testcaseID_;
          onChanged();
        }
        if (!other.getRecordID().isEmpty()) {
          recordID_ = other.recordID_;
          onChanged();
        }
        if (other.getIsPass() != false) {
          setIsPass(other.getIsPass());
        }
        if (other.getStartTime() != 0L) {
          setStartTime(other.getStartTime());
        }
        if (other.getEndTime() != 0L) {
          setEndTime(other.getEndTime());
        }
        if (!other.getResultStr().isEmpty()) {
          resultStr_ = other.resultStr_;
          onChanged();
        }
        if (!other.getExceptionStr().isEmpty()) {
          exceptionStr_ = other.exceptionStr_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chi.ssetest.protos.TestRecord.TestExecutionRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chi.ssetest.protos.TestRecord.TestExecutionRecord) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object jobID_ = "";
      /**
       * <code>string jobID = 1;</code>
       */
      public java.lang.String getJobID() {
        java.lang.Object ref = jobID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jobID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string jobID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getJobIDBytes() {
        java.lang.Object ref = jobID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jobID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string jobID = 1;</code>
       */
      public Builder setJobID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        jobID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string jobID = 1;</code>
       */
      public Builder clearJobID() {
        
        jobID_ = getDefaultInstance().getJobID();
        onChanged();
        return this;
      }
      /**
       * <code>string jobID = 1;</code>
       */
      public Builder setJobIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        jobID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object runnerID_ = "";
      /**
       * <code>string runnerID = 2;</code>
       */
      public java.lang.String getRunnerID() {
        java.lang.Object ref = runnerID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          runnerID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string runnerID = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRunnerIDBytes() {
        java.lang.Object ref = runnerID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          runnerID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string runnerID = 2;</code>
       */
      public Builder setRunnerID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        runnerID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string runnerID = 2;</code>
       */
      public Builder clearRunnerID() {
        
        runnerID_ = getDefaultInstance().getRunnerID();
        onChanged();
        return this;
      }
      /**
       * <code>string runnerID = 2;</code>
       */
      public Builder setRunnerIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        runnerID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object testcaseID_ = "";
      /**
       * <code>string testcaseID = 3;</code>
       */
      public java.lang.String getTestcaseID() {
        java.lang.Object ref = testcaseID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          testcaseID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string testcaseID = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTestcaseIDBytes() {
        java.lang.Object ref = testcaseID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          testcaseID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string testcaseID = 3;</code>
       */
      public Builder setTestcaseID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        testcaseID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string testcaseID = 3;</code>
       */
      public Builder clearTestcaseID() {
        
        testcaseID_ = getDefaultInstance().getTestcaseID();
        onChanged();
        return this;
      }
      /**
       * <code>string testcaseID = 3;</code>
       */
      public Builder setTestcaseIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        testcaseID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object recordID_ = "";
      /**
       * <code>string recordID = 4;</code>
       */
      public java.lang.String getRecordID() {
        java.lang.Object ref = recordID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          recordID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string recordID = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRecordIDBytes() {
        java.lang.Object ref = recordID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          recordID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string recordID = 4;</code>
       */
      public Builder setRecordID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        recordID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string recordID = 4;</code>
       */
      public Builder clearRecordID() {
        
        recordID_ = getDefaultInstance().getRecordID();
        onChanged();
        return this;
      }
      /**
       * <code>string recordID = 4;</code>
       */
      public Builder setRecordIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        recordID_ = value;
        onChanged();
        return this;
      }

      private boolean isPass_ ;
      /**
       * <code>bool isPass = 5;</code>
       */
      public boolean getIsPass() {
        return isPass_;
      }
      /**
       * <code>bool isPass = 5;</code>
       */
      public Builder setIsPass(boolean value) {
        
        isPass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isPass = 5;</code>
       */
      public Builder clearIsPass() {
        
        isPass_ = false;
        onChanged();
        return this;
      }

      private long startTime_ ;
      /**
       * <code>int64 startTime = 6;</code>
       */
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <code>int64 startTime = 6;</code>
       */
      public Builder setStartTime(long value) {
        
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 startTime = 6;</code>
       */
      public Builder clearStartTime() {
        
        startTime_ = 0L;
        onChanged();
        return this;
      }

      private long endTime_ ;
      /**
       * <code>int64 endTime = 7;</code>
       */
      public long getEndTime() {
        return endTime_;
      }
      /**
       * <code>int64 endTime = 7;</code>
       */
      public Builder setEndTime(long value) {
        
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 endTime = 7;</code>
       */
      public Builder clearEndTime() {
        
        endTime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object resultStr_ = "";
      /**
       * <code>string resultStr = 8;</code>
       */
      public java.lang.String getResultStr() {
        java.lang.Object ref = resultStr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resultStr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string resultStr = 8;</code>
       */
      public com.google.protobuf.ByteString
          getResultStrBytes() {
        java.lang.Object ref = resultStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resultStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string resultStr = 8;</code>
       */
      public Builder setResultStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resultStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string resultStr = 8;</code>
       */
      public Builder clearResultStr() {
        
        resultStr_ = getDefaultInstance().getResultStr();
        onChanged();
        return this;
      }
      /**
       * <code>string resultStr = 8;</code>
       */
      public Builder setResultStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resultStr_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object exceptionStr_ = "";
      /**
       * <code>string exceptionStr = 9;</code>
       */
      public java.lang.String getExceptionStr() {
        java.lang.Object ref = exceptionStr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          exceptionStr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string exceptionStr = 9;</code>
       */
      public com.google.protobuf.ByteString
          getExceptionStrBytes() {
        java.lang.Object ref = exceptionStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exceptionStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string exceptionStr = 9;</code>
       */
      public Builder setExceptionStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        exceptionStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string exceptionStr = 9;</code>
       */
      public Builder clearExceptionStr() {
        
        exceptionStr_ = getDefaultInstance().getExceptionStr();
        onChanged();
        return this;
      }
      /**
       * <code>string exceptionStr = 9;</code>
       */
      public Builder setExceptionStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        exceptionStr_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:stock_testing.TestExecutionRecord)
    }

    // @@protoc_insertion_point(class_scope:stock_testing.TestExecutionRecord)
    private static final com.chi.ssetest.protos.TestRecord.TestExecutionRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.chi.ssetest.protos.TestRecord.TestExecutionRecord();
    }

    public static com.chi.ssetest.protos.TestRecord.TestExecutionRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestExecutionRecord>
        PARSER = new com.google.protobuf.AbstractParser<TestExecutionRecord>() {
      @java.lang.Override
      public TestExecutionRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestExecutionRecord(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestExecutionRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestExecutionRecord> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.chi.ssetest.protos.TestRecord.TestExecutionRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stock_testing_TestExecutionRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stock_testing_TestExecutionRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014record.proto\022\rstock_testing\"\271\001\n\023TestEx" +
      "ecutionRecord\022\r\n\005jobID\030\001 \001(\t\022\020\n\010runnerID" +
      "\030\002 \001(\t\022\022\n\ntestcaseID\030\003 \001(\t\022\020\n\010recordID\030\004" +
      " \001(\t\022\016\n\006isPass\030\005 \001(\010\022\021\n\tstartTime\030\006 \001(\003\022" +
      "\017\n\007endTime\030\007 \001(\003\022\021\n\tresultStr\030\010 \001(\t\022\024\n\014e" +
      "xceptionStr\030\t \001(\tB$\n\026com.chi.ssetest.pro" +
      "tosB\nTestRecordb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_stock_testing_TestExecutionRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stock_testing_TestExecutionRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stock_testing_TestExecutionRecord_descriptor,
        new java.lang.String[] { "JobID", "RunnerID", "TestcaseID", "RecordID", "IsPass", "StartTime", "EndTime", "ResultStr", "ExceptionStr", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
